/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiRoomsGet200ResponseInner,
} from '../models';
import {
    ApiRoomsGet200ResponseInnerFromJSON,
    ApiRoomsGet200ResponseInnerToJSON,
} from '../models';

/**
 * RoomsApi - interface
 * 
 * @export
 * @interface RoomsApiInterface
 */
export interface RoomsApiInterface {
    /**
     * Retrieve a list of all rooms
     * @summary Get list of rooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomsApiInterface
     */
    apiRoomsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiRoomsGet200ResponseInner>>>;

    /**
     * Retrieve a list of all rooms
     * Get list of rooms
     */
    apiRoomsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiRoomsGet200ResponseInner>>;

}

/**
 * 
 */
export class RoomsApi extends runtime.BaseAPI implements RoomsApiInterface {

    /**
     * Retrieve a list of all rooms
     * Get list of rooms
     */
    async apiRoomsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiRoomsGet200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/rooms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiRoomsGet200ResponseInnerFromJSON));
    }

    /**
     * Retrieve a list of all rooms
     * Get list of rooms
     */
    async apiRoomsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiRoomsGet200ResponseInner>> {
        const response = await this.apiRoomsGetRaw(initOverrides);
        return await response.value();
    }

}
