import React, {useState} from "react";
import {RoomApi} from "../../../../../autogenerated/gf-server-api/apis/RoomApi";
import {IRoom} from "../../../../model/room";


export const ApartmentsType = ({room}:{room:IRoom}) => {

  const [type, setType] = useState(room.apartmentsType);
  const [isDisabled, setIsDisabled] = useState(true);
  const roomApi = new RoomApi;
  const roomTypes = ["Single", "Double", "Twin"];

  const saveHandler = async () => {
    setIsDisabled(true);
    room.apartmentsType = type;
    console.log(room);

    try {
      room.id && await roomApi.apiRoomsRoomIdPut({roomId: room.id, body: room});
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <li>
      <p>
        Room type
      </p>
      <select value={type}
        disabled={isDisabled}
        onChange={(e) => setType(e.target.value)}
      >
        {roomTypes.map(roomType => (
          <option key={roomType}
            value={roomType}
          >
            {roomType}
          </option>
        ))}
      </select>
      {isDisabled ?
        (
          <button onClick={() => setIsDisabled(false)}>
            Edit
          </button>
        )
        :
        (
          <button onClick={saveHandler}>
            Save
          </button>
        )}
    </li>
  );
};