import {RoomApi} from "../../autogenerated/gf-server-api/apis/RoomApi";
import {RoomsApi} from "../../autogenerated/gf-server-api/apis/RoomsApi";
import {AddRoom, Room} from "../model/Room/Room";

export const saveRoom = async (room: Room) => {
  const roomApi = new RoomApi;
  try {
    if (room.id) {
      await roomApi.apiRoomsRoomIdPut({roomId: room.id, body: room});
    }
  } catch (error) {
    console.log(error);
  }
};

export const getRooms = async () => {
  const roomsApi = new RoomsApi;
  const res = await roomsApi.apiRoomsGet();
  return res as Room[];
};

export const getRoom = async (id:string) => {
  const roomApi = new RoomApi;
  const res = await roomApi.apiRoomsRoomIdGet({roomId: id});
  return res as Room;
};

export const deleteRoom = async (id: string) => {
  const roomApi = new RoomApi;
  await roomApi.apiRoomsRoomIdDelete({roomId: id});
};

export const postRoom = async (room: AddRoom) => {
  const roomsApi = new RoomsApi;
  await roomsApi.apiRoomsPost({body: room});
};