import React, {useRef, useState} from "react";
import {useDictionary} from "../DictionaryContext/useDictionary";
import {PageBorder} from "../../component/pageBorder/PageBorder";
import {MailApiService} from "src/service/MailApi/MailApi";
import {ApiAskAdminPostRequest} from "src/autogenerated/gf-server-api/models/ApiAskAdminPostRequest";
import styles from "./ContactsPage.module.scss";
import {Button} from "gf-ui-lib/components/Button/Button";

const defaultAskAdminFormData: ApiAskAdminPostRequest = {name: "", email: "", phone: "", message: ""};

export const ContactsPage = () => {
  const {contactsPage, askAdminForm} = useDictionary().dictionary;
  const [askAdminFormData, setAskAdminFormData] = useState<ApiAskAdminPostRequest>(defaultAskAdminFormData);

  const sendMail = async () => {
    const res = await MailApiService.askAdminMessage({apiAskAdminPostRequest: askAdminFormData});
  };

  const onSubmit = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    setAskAdminFormData(defaultAskAdminFormData);
    await sendMail();
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setAskAdminFormData({...askAdminFormData, [e.target.name]: e.target.value});
  };

  const formToSubmit = useRef<HTMLFormElement>(null);

  return (
    <PageBorder>
      <div className={styles.wrap}>
        <div className={styles.contacts}>
          <h1 className={styles.title}>
            {contactsPage.title}
          </h1>
          <div className={styles.contactsData}>
            <div className={styles.minititle}>
              {contactsPage.phone}
            </div>
            <p className={styles.text}>
              +12346789
            </p>
            <div className={styles.minititle}>
              {contactsPage.email}
            </div>
            <p className={styles.text}>
              goldenFleece@gmain.com
            </p>
            <div className={styles.minititle}>
              {contactsPage.address}
            </div>
            <p className={styles.text}>
              {contactsPage.street}
              ,
            </p>
            <p className={styles.text}>
              {contactsPage.location}
            </p>
          </div>
        </div>
        <form
          onSubmit={onSubmit}
          ref={formToSubmit}
          className={styles.form}
        >
          <div className={styles.formGoup}>
            <label
              className={styles.label}
              htmlFor="text"
            >
              {askAdminForm.name}
            </label>
            <input
              type="text"
              className={styles.input}
              id="text"
              placeholder={askAdminForm.name}
              name="name"
              value={askAdminFormData.name}
              onChange={handleChange}
              required
            />
          </div>
          <div className={styles.formGoup}>
            <label
              className={styles.label}
              htmlFor="email"
            >
              {askAdminForm.email}
            </label>
            <input
              type="email"
              className={styles.input}
              id="email"
              placeholder={askAdminForm.email}
              name="email"
              value={askAdminFormData.email}
              onChange={handleChange}
              required
            />
          </div>
          <div className={styles.formGoup}>
            <label
              className={styles.label}
              htmlFor="phone"
            >
              {askAdminForm.phone}
            </label>
            <input
              type="text"
              className={styles.input}
              id="phone"
              placeholder={askAdminForm.phone}
              name="phone"
              value={askAdminFormData.phone}
              onChange={handleChange}
              required
            />
          </div>
          <div className={styles.formGoup}>
            <label
              className={styles.label}
              htmlFor="message"
            >
              {askAdminForm.message}
            </label>
            <input
              type="text"
              className={styles.input}
              id="message"
              placeholder={askAdminForm.message}
              name="message"
              value={askAdminFormData.message}
              onChange={handleChange}
              required
            />
          </div>
          <Button
            onClick={() => formToSubmit.current?.submit()}
            value={askAdminForm.buttonText}
          />
        </form>
      </div>
    </PageBorder>
  );
};