import * as React from "react";
import {IRoom} from "../../../model/room";
import {RoomApi} from "../../../../autogenerated/gf-server-api/apis/RoomApi";
import {useState} from "react";

export const Price = ({room}:{room:IRoom}) => {
  const [price, setPrice] = useState(String(room.price));
  const [isDisabled, setIsDisabled] = useState(true);
  const roomApi = new RoomApi;

  const saveHandler = async () => {
    setIsDisabled(true);
    // room.apartmentsType = type;
    console.log(room);


    try {
      if (room.id) {
        const res = await roomApi.apiRoomsRoomIdGet({roomId: room.id});
        console.log("res", res);
        // const res = await roomApi.apiRoomsRoomIdPut({roomId: room.id, body: room});
        // console.log("res", res);
      }
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <li>
      <label htmlFor={`price-${room.id}`}>
        Room price
      </label>
      <input type="text"
        id={`price-${room.id}`}
        value={price}
        onChange={(e) => setPrice(e.target.value)}
        disabled={isDisabled}
      />
      {isDisabled ?
        (
          <button onClick={() => setIsDisabled(false)}>
            Edit
          </button>
        )
        :
        (
          <button onClick={saveHandler}>
            Save
          </button>
        )}
    </li>
  );
};