import {useState} from "react";
import {useModalVisibilityContext, useDictionary} from "src/logic/DictionaryContext/useDictionary";
import {MailApiService} from "src/service/MailApi/MailApi";
import {ApiBookingRequestPostRequest} from "src/autogenerated/gf-server-api/models/ApiBookingRequestPostRequest";
import {Button} from "gf-ui-lib/src/components/Button/Button";
import {useFilterRooms} from "src/component/filter/FilterContext";
import styles from "src/logic/bookingPage/form/Form.module.scss";

type RoomProps = {
  roomNumber: string | null;
}

const DEFAULT_INPUT_STRING = "";
const DEFAULT_INPUT_NUMBER = 0;

const defaultBookingFormData: ApiBookingRequestPostRequest = {
  email: DEFAULT_INPUT_STRING,
  name: DEFAULT_INPUT_STRING,
  dateIn: DEFAULT_INPUT_STRING,
  dateOut: DEFAULT_INPUT_STRING,
  roomNumber: DEFAULT_INPUT_NUMBER,
  adultsAmount: DEFAULT_INPUT_NUMBER,
  childrenAmount: DEFAULT_INPUT_NUMBER,
};

export const Form = (props: RoomProps) => {
  const {adultsValue, childrenValue, dateInValue, dateOutValue} = useFilterRooms();
  const {bookingRoomForm} = useDictionary().dictionary;
  const {setIsModalActive, setIsModalCheckMailActive} = useModalVisibilityContext();
  const [bookingFormData, setBookingFormData] = useState<ApiBookingRequestPostRequest>(defaultBookingFormData);

  const sendMail = async () => {
    const res = await MailApiService.bookingMessage({apiBookingRequestPostRequest: bookingFormData});
  };

  const onSubmit = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsModalCheckMailActive(true);
    setIsModalActive(false);
    await sendMail();
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setBookingFormData({...bookingFormData, [e.target.name]: e.target.value});
  };

  const handleChangeRoom = (e: React.ChangeEvent<HTMLInputElement>) => {
    setBookingFormData({...bookingFormData, [e.target.name]: props.roomNumber});
  };

  return (
    <div>
      <form
        onSubmit={onSubmit}
        className={styles.form}
      >
        <div className={styles.formGoup}>
          <label className={styles.label}>
            {bookingRoomForm.email}
            <input
              type="email"
              className={styles.input}
              placeholder={bookingRoomForm.email}
              name={bookingRoomForm.email}
              value={bookingFormData.email}
              onChange={handleChange}
              required
            />
          </label>
        </div>
        <div className={styles.formGoup}>
          <label className={styles.label}>
            {bookingRoomForm.name}
            <input
              type="text"
              className={styles.input}
              placeholder={bookingRoomForm.name}
              name={bookingRoomForm.name}
              value={bookingFormData.name}
              onChange={handleChange}
              required
            />
          </label>
        </div>
        <div className={styles.row}>
          <div className={styles.formGoup}>
            <label className={styles.label}>
              {bookingRoomForm.dateIn}
              <input
                type="date"
                className={styles.input2}
                name={bookingRoomForm.dateIn}
                value={dateInValue}
                onChange={handleChange}
                required
              />
            </label>
          </div>
          <div className={styles.formGoup}>
            <label className={styles.label}>
              {bookingRoomForm.dateOut}
              <input
                type="date"
                className={styles.input2}
                name={bookingRoomForm.dateOut}
                value={dateOutValue}
                onChange={handleChange}
              />
            </label>
          </div>
        </div>
        <div className={styles.row}>
          <div className={styles.formGroup}>
            <label className={styles.label}>
              {bookingRoomForm.roomNumber}
              <input
                type="text"
                className={styles.input}
                name={bookingRoomForm.roomNumber}
                value={props.roomNumber ?? undefined}
                onChange={handleChangeRoom}
                required
              />
            </label>
          </div>
          <div className={styles.row}>
            <div className={styles.formGroup}>
              <label className={styles.label}>
                {bookingRoomForm.adultsAmount}
                <input
                  type="text"
                  className={styles.input}
                  name={bookingRoomForm.adultsAmount}
                  value={adultsValue}
                  onChange={handleChange}
                  required
                />
              </label>
            </div>
          </div>
          <div className={styles.row}>
            <div className={styles.formGroup}>
              <label className={styles.label}>
                {bookingRoomForm.childrenAmount}
                <input
                  type="text"
                  className={styles.input}
                  name={bookingRoomForm.childrenAmount}
                  value={childrenValue}
                  onChange={handleChange}
                  required
                />
              </label>
            </div>
          </div>
        </div>
        <Button
          type="submit"
          onClick={() => onSubmit}
          value={bookingRoomForm.buttonText}
        />
      </form>
    </div>
  );
};