import {useEffect, useState} from "react";
import {Room} from "src/autogenerated/gf-server-api/models/Room";
import {RoomItem} from "src/logic/rooms/roomsPage/roomBlock/roomItem/RoomItem";
import {RoomApiService} from "src/service/RoomApi/RoomApi";
import {Loader} from "gf-ui-lib/components/Loader/Loader";

export const RoomsBlock = () => {
  const [rooms, setRooms] = useState<Room[] | null>(null);

  const initRooms = async () => {
    const roomsList = await RoomApiService.getAllRooms();
    setRooms(roomsList);
  };

  useEffect(() => {
    initRooms();
  }, []);

  const renderRoomItem = (roomsList: Room[]) => {
    return roomsList.map(room => (
      <RoomItem
        key={room.id}
        room={room}
      />
    ));
  };

  // if data not initialized yet
  if (!rooms) {
    return <Loader />;
  }

  return (
    <div>
      {renderRoomItem(rooms)}
    </div>
  );

};

