import swaggerJsDoc from "swagger-jsdoc";
import swaggerDefinition from "./autogenerated/swaggerConfiguration.json";
import {config} from "dotenv";

config();

export const GF_SERVER_RESOURCES_HOST = process.env.GF_SERVER_RESOURCES_HOST;
export const GF_SERVER_RESOURCES_PORT = process.env.GF_SERVER_RESOURCES_PORT;

swaggerDefinition.servers[0].url = `${GF_SERVER_RESOURCES_HOST}:${GF_SERVER_RESOURCES_PORT}`;

const swaggerJsDocOptions = {
  swaggerDefinition,
  apis: ["./src/routes/*.ts", "./src/model/*.ts"],
};

export const apiSpec = swaggerJsDoc(swaggerJsDocOptions);