import React, {useEffect, useState} from "react";
import {SideMenu} from "../../component/sideMenu/sideMenu";
import styles from "./mainPage.module.scss";
import {RoomsApi} from "../../../autogenerated/gf-server-api/apis/RoomsApi";
import {ApartmentsType} from "./apartmentType/ApartmentType";
import {IRoom} from "../../model/room";

export const MainPage = () => {
  const roomsApi = new RoomsApi;
  const [rooms, setRooms] = useState<IRoom[]>([]);

  const getRooms = async () => {
    const res = await roomsApi.apiRoomsGet();
    setRooms(res);
  };

  useEffect(() => {
    getRooms();
  }, []);

  return (
    <div className={styles.mainPage}>
      <SideMenu />
      <div className={styles.rooms}>
        {rooms.map(room => (
          <ul key={room.id}
            className={styles.room}
          >
            <ApartmentsType room={room} />
            <li>
              <label htmlFor={`desc-${room.id}`}>
                Room description
              </label>
              <input type="text"
                id={`desc-${room.id}`}
                defaultValue={room.description}
              />
            </li>
            <li>
              <label htmlFor={`desc-long-${room.id}`}>
                Room long description
              </label>
              <input type="text"
                id={`desc-long-${room.id}`}
                defaultValue={room.descriptionLong}
              />
            </li>
            <li>
              <label htmlFor={`services-${room.id}`}>
                Room services
              </label>
              <input type="text"
                id={`services-${room.id}`}
                defaultValue={room.services}
              />
            </li>
            <li>
              <label htmlFor={`rating-${room.id}`}>
                Room rating
              </label>
              <input type="text"
                id={`rating-${room.id}`}
                defaultValue={room.rating}
              />
            </li>
            <li>
              <label htmlFor={`price-${room.id}`}>
                Room price
              </label>
              <input type="text"
                id={`price-${room.id}`}
                defaultValue={room.price}
              />
            </li>
            <li>
              Promo
              <br />
              <img width={200}
                height={200}
                src={room.promo}
                alt="room-promo"
              />
            </li>

            <li>
              Slider
              <div className={styles.slides}>
                <img width={200}
                  height={200}
                  src={room.slider}
                  alt="slide"
                />
                <img width={200}
                  height={200}
                  src={room.slider2}
                  alt="slide2"
                />
                <img width={200}
                  height={200}
                  src={room.slider3}
                  alt="slide3"
                />
                <img width={200}
                  height={200}
                  src={room.slider4}
                  alt="slide4"
                />
                <img width={200}
                  height={200}
                  src={room.slider5}
                  alt="slide5"
                />
              </div>
            </li>

          </ul>
        ))}
      </div>
    </div>
  );
};
