import {exec, ExecException} from "child_process";

const errorHandler = (error: ExecException | null, stdout: string, stderr: string) => {
  if (error || stderr) {
    console.log(stdout);
    console.error(error, stderr);
  }
};

exec(
  "pnpm \
  openapi-generator-cli generate -i ../gf-server-resources/autogenerated/swagger.yml \
  -g typescript-fetch \
  -o autogenerated/gf-server-resources \
  --additional-properties=supportsES6=true,withInterfaces=true --skip-validate-spec",
  errorHandler,
);