import React, {useEffect, useState} from "react";
import {Room} from "../../model/Room";
import {RoomsApi} from "../../../autogenerated/gf-server-api/apis/RoomsApi";

export function useRooms() {
  const roomsApi = new RoomsApi;
  const [rooms, setRooms] = useState<Array<Room>>([]);
  async function getRooms() {
    try {
      const res = await roomsApi.apiRoomsGet();
      setRooms(res);
    } catch (e) {
      console.error(e);
    }
  }

  useEffect(() => {
    getRooms();
  }, []);

  return {rooms};
}