import {readFileSync, writeFileSync, mkdirSync} from "fs";
import path from "path";
import {GF_SERVER_API_HOST, GF_SERVER_API_PORT} from "../swagger";

mkdirSync(path.resolve(__dirname, "../autogenerated"), {recursive: true});

const swaggerConfigurationTemplateString = readFileSync(
  path.resolve(__dirname, "../static/swaggerConfigurationTemplate.json"),
  "utf8",
);

const swaggerConfigurationTemplate = JSON.parse(swaggerConfigurationTemplateString);
swaggerConfigurationTemplate.servers[0].url = `${GF_SERVER_API_HOST}:${GF_SERVER_API_PORT}`;

const swaggerConfiguration = JSON.stringify(swaggerConfigurationTemplate);
writeFileSync(
  path.resolve(__dirname, "../autogenerated/swaggerConfiguration.json"),
  swaggerConfiguration,
);
