import {RoomApi, RoomsApi} from "../../autogenerated/gf-server-api/index";
import {Configuration} from "../../autogenerated/gf-server-api/runtime";

const configuration = new Configuration({basePath: process.env.API_BASE_PATH});

export const roomsApi = new RoomsApi(configuration);
export const roomApi = new RoomApi(configuration);