import {RoomApi, RoomsApi, MailApi, Configuration} from "src/../autogenerated/gf-server-api/index";

const configuration = new Configuration({basePath: process.env.API_BASE_PATH});

export const roomsApi = new RoomsApi(configuration);
export const roomApi = new RoomApi(configuration);
export const mailApi = new MailApi(configuration);