import {RoomsApi} from "../../autogenerated/gf-server-api/apis/RoomsApi";

export const getRooms = async () => {
  const roomsApi = new RoomsApi;
  const res = await roomsApi.apiRoomsGet();
  return res;
};