import {RoomsApi} from "../../autogenerated/gf-server-api/apis/RoomsApi";
import {RoomApi} from "../../autogenerated/gf-server-api/apis/RoomApi";
import {Room} from "../model/room";

export const getRooms = async () => {
  const roomsApi = new RoomsApi;
  const res = await roomsApi.apiRoomsGet();
  return res as Room[];
};

export const getRoomNumber = (id:string | undefined) => {
  return id && +id < 10 ? `0${Number(id) + 1}` : id;
};

export const getRoom = async (id:string) => {
  const roomApi = new RoomApi;
  const res = await roomApi.apiRoomsRoomIdGet({roomId: id});
  return res as Room;
};

export const roomInit = (room:Room) => {
  return Object.keys(room).length;
};

export const roomsInit = (rooms:Room[]) => {
  return rooms.length;
};