import {RoomsApi} from "../../autogenerated/gf-server-api/apis/RoomsApi";

export const getRooms = async () => {
  const roomsApi = new RoomsApi;
  const res = await roomsApi.apiRoomsGet();
  return res;
};

export const getRoomNumber = (id:string | undefined) => {
  return id && +id < 10 ? `0${Number(id) + 1}` : id;
};