import {mailApi} from "src/service/ApiInitialization";
import {ApiAskAdminPostOperationRequest, ApiBookingRequestPostOperationRequest} from "src/autogenerated/gf-server-api/apis/MailApi";

export class MailApiService {

  public static async askAdminMessage(apiAskAdminPostRequest: ApiAskAdminPostOperationRequest) {
    const askAdminMessage = await mailApi.apiAskAdminPost(apiAskAdminPostRequest);
  }

  public static async bookingMessage(apiBookingRequestPostRequest: ApiBookingRequestPostOperationRequest) {
    const bookingMessage = await mailApi.apiBookingRequestPost(apiBookingRequestPostRequest);
  }

}
