import {Currency} from "src/model/Currency";
import {Price as PriceDTO} from "src/autogenerated/gf-server-api/models/Price";

export class Price {

  /**
   * Price currency
   */
  private currency: Currency;

  /**
   * Price amount
   */
  private amount: number;

  constructor(currency: Currency, amount: number) {
    this.currency = currency;
    this.amount = amount;
  }

  /**
   * Get formatted price
   */
  public getFullPrice() {
    return `${this.amount} ${this.currency}`;
  }

  /**
   * Get price amount
   */
  public getPriceAmount() {
    return this.amount;
  }

  /**
   * Set new price amount
   */
  public setNewPrice(amount: number) {
    return this.amount = amount;
  }

  /**
   * Convert class Price to DTO object
   */
  public toJSON(): PriceDTO {
    return {
      currency: this.currency,
      amount: this.amount,
    };
  }

}