/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRoomsGet200ResponseInner
 */
export interface ApiRoomsGet200ResponseInner {
    /**
     * check in date yyyy-mm-dd
     * @type {string}
     * @memberof ApiRoomsGet200ResponseInner
     */
    dateIn: string;
    /**
     * check out date yyyy-mm-dd
     * @type {string}
     * @memberof ApiRoomsGet200ResponseInner
     */
    dateOut: string;
}

/**
 * Check if a given object implements the ApiRoomsGet200ResponseInner interface.
 */
export function instanceOfApiRoomsGet200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dateIn" in value;
    isInstance = isInstance && "dateOut" in value;

    return isInstance;
}

export function ApiRoomsGet200ResponseInnerFromJSON(json: any): ApiRoomsGet200ResponseInner {
    return ApiRoomsGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiRoomsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRoomsGet200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateIn': json['dateIn'],
        'dateOut': json['dateOut'],
    };
}

export function ApiRoomsGet200ResponseInnerToJSON(value?: ApiRoomsGet200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateIn': value.dateIn,
        'dateOut': value.dateOut,
    };
}

