import {exec, ExecException} from "child_process";

const errorHandler = (error: ExecException | null, stdout: string, stderr: string) => {
  if (error || stderr) {
    console.log(stdout);
    console.error(error, stderr);
  }
};

exec(
  "pnpm \
  swagger-jsdoc -d autogenerated/swaggerConfiguration.json \
  src/routes/*.ts src/model/*.ts \
  -o autogenerated/swagger.yml",
  errorHandler,
);