/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Apartments = {
    Single: 'Single',
    Double: 'Double',
    Twin: 'Twin'
} as const;
export type Apartments = typeof Apartments[keyof typeof Apartments];


export function ApartmentsFromJSON(json: any): Apartments {
    return ApartmentsFromJSONTyped(json, false);
}

export function ApartmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Apartments {
    return json as Apartments;
}

export function ApartmentsToJSON(value?: Apartments | null): any {
    return value as any;
}

