/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Period
 */
export interface Period {
    /**
     * Day of arrival.
     * @type {Date}
     * @memberof Period
     */
    dateIn: Date;
    /**
     * Departure day.
     * @type {Date}
     * @memberof Period
     */
    dateOut: Date;
}

/**
 * Check if a given object implements the Period interface.
 */
export function instanceOfPeriod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dateIn" in value;
    isInstance = isInstance && "dateOut" in value;

    return isInstance;
}

export function PeriodFromJSON(json: any): Period {
    return PeriodFromJSONTyped(json, false);
}

export function PeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Period {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateIn': (new Date(json['dateIn'])),
        'dateOut': (new Date(json['dateOut'])),
    };
}

export function PeriodToJSON(value?: Period | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateIn': (value.dateIn.toISOString().substr(0,10)),
        'dateOut': (value.dateOut.toISOString().substr(0,10)),
    };
}

