/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Customer } from './Customer';
import {
    CustomerFromJSON,
    CustomerFromJSONTyped,
    CustomerToJSON,
} from './Customer';
import type { Period } from './Period';
import {
    PeriodFromJSON,
    PeriodFromJSONTyped,
    PeriodToJSON,
} from './Period';

/**
 * 
 * @export
 * @interface RoomPaid
 */
export interface RoomPaid {
    /**
     * 
     * @type {Customer}
     * @memberof RoomPaid
     */
    customer: Customer;
    /**
     * 
     * @type {Period}
     * @memberof RoomPaid
     */
    period: Period;
}

/**
 * Check if a given object implements the RoomPaid interface.
 */
export function instanceOfRoomPaid(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "customer" in value;
    isInstance = isInstance && "period" in value;

    return isInstance;
}

export function RoomPaidFromJSON(json: any): RoomPaid {
    return RoomPaidFromJSONTyped(json, false);
}

export function RoomPaidFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomPaid {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': CustomerFromJSON(json['customer']),
        'period': PeriodFromJSON(json['period']),
    };
}

export function RoomPaidToJSON(value?: RoomPaid | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': CustomerToJSON(value.customer),
        'period': PeriodToJSON(value.period),
    };
}

