/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomInfo } from './RoomInfo';
import {
    RoomInfoFromJSON,
    RoomInfoFromJSONTyped,
    RoomInfoToJSON,
} from './RoomInfo';

/**
 * 
 * @export
 * @interface Dictionary
 */
export interface Dictionary {
    /**
     * 
     * @type {RoomInfo}
     * @memberof Dictionary
     */
    en: RoomInfo;
    /**
     * 
     * @type {RoomInfo}
     * @memberof Dictionary
     */
    ru: RoomInfo;
    /**
     * 
     * @type {RoomInfo}
     * @memberof Dictionary
     */
    ge: RoomInfo;
}

/**
 * Check if a given object implements the Dictionary interface.
 */
export function instanceOfDictionary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "en" in value;
    isInstance = isInstance && "ru" in value;
    isInstance = isInstance && "ge" in value;

    return isInstance;
}

export function DictionaryFromJSON(json: any): Dictionary {
    return DictionaryFromJSONTyped(json, false);
}

export function DictionaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dictionary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'en': RoomInfoFromJSON(json['en']),
        'ru': RoomInfoFromJSON(json['ru']),
        'ge': RoomInfoFromJSON(json['ge']),
    };
}

export function DictionaryToJSON(value?: Dictionary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'en': RoomInfoToJSON(value.en),
        'ru': RoomInfoToJSON(value.ru),
        'ge': RoomInfoToJSON(value.ge),
    };
}

