/* tslint:disable */
/* eslint-disable */
/**
 * Golden Fleece API
 * A simple REST API for providing basic CRUD-access to the employees in a Golden Fleece database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RoomServices = {
    WiFi: 'WiFi',
    Laundry: 'Laundry',
    TeaCoffeeMaker: 'TeaCoffeeMaker',
    Heating: 'Heating',
    AirportShuttle: 'AirportShuttle'
} as const;
export type RoomServices = typeof RoomServices[keyof typeof RoomServices];


export function RoomServicesFromJSON(json: any): RoomServices {
    return RoomServicesFromJSONTyped(json, false);
}

export function RoomServicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomServices {
    return json as RoomServices;
}

export function RoomServicesToJSON(value?: RoomServices | null): any {
    return value as any;
}

