import React, {useEffect, useState} from "react";
import {IRoom} from "../../model/room";
import {RoomsApi} from "../../../autogenerated/gf-server-api/apis/RoomsApi";
import styles from "./rooms.module.scss";
import {Room} from "./room/Room";

export const Rooms = () => {
  const roomsApi = new RoomsApi;
  const [rooms, setRooms] = useState<IRoom[]>([]);

  const getRooms = async () => {
    const res = await roomsApi.apiRoomsGet();
    setRooms(res);
  };

  useEffect(() => {
    getRooms();
  }, []);

  return (
    <div className={styles.rooms}>
      {rooms.map(room => (
        <Room key={room.id}
          room={room}
        />
      ))}
    </div>
  );
};