import {exec} from "child_process";
import {errorHandler} from "./utils/errorHandler";

exec(
  "pnpm run -r removeAutogenerated",
  errorHandler,
);

exec(
  "pnpm dlx rimraf node_modules",
  errorHandler,
);