import {roomApi, roomsApi} from "src/service/ApiInitialization";
import {Room as RoomDTO} from "src/autogenerated/gf-server-api/models/Room";
import {Room} from "src/model/Room/Room";
import {Price} from "src/model/Price/Price";
import {Currency} from "src/model/Price/Currency";
import {RoomServices} from "src/model/Room/RoomServices";

const roomDTOToBusinessConverter = (roomRaw: RoomDTO) => new Room({
  ...roomRaw,
  price: new Price(Currency[roomRaw.price.currency], roomRaw.price.amount),
  services: roomRaw.services.map((service) => RoomServices[service]),
});

export class RoomApiService {

  public static async getAllRooms() {
    const roomsRaw: RoomDTO[] = await roomsApi.apiRoomsGet();
    const rooms = roomsRaw.map(roomDTOToBusinessConverter);
    return rooms;
  }

  public static async getRoomById(id: string) {
    const roomRaw: RoomDTO = await roomApi.apiRoomsRoomIdGet({roomId: id});
    const room = roomDTOToBusinessConverter(roomRaw);
    return room;
  }

}
