name: check PR all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm i -g pnpm
        pnpm install
        pnpm buildAll

    - name: Cypress run gf-ui-lib
      uses: cypress-io/github-action@v5
      with:
        project: ./gf-ui-lib
        browser: chrome
        start: npm startAll
    
    - name: Cypress run gf-e2e-test
      uses: cypress-io/github-action@v5
      with:
        project: ./gf-e2e-test
        browser: chrome
        start: npm startAll
      env:
        EXAMPLE_ENV_VARIABLE: ${{ secrets.EXAMPLE_ENV_VARIABLE }}
