name: check PR all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm -g pnpm
        pnpm ci
        pnpm buildAll

    - name: Cypress run
      uses: cypress-io/github-action@v5
      # with:
      #   build: npm run build
      #   start: npm start
      run: pnpm run testAll
